[package]
name = "network"
authors = ["Abdulsemiu Atanda <semiu@live.com>"]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[lib]
name="network"
path="src/lib.rs"

[dependencies]
diesel = { version = "2.3.13", optional = true, features = ["extras", "postgres"] }
log = "0.4.34"
redis = { version = "1.7.0", optional = true }
reqwest = { version = "0.13.5", features = ["json"], optional = true }
serde = "1.0.229"
serde_derive = "1.0.229"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
httpmock = "0.8.3"
serde_json = "1"

[features]
default = ["http"]
database = ["diesel"]
keystore = ["redis"]
http = ["reqwest"]
spec = ["database"]
